### ISSUE TITLE
Auto create mxd

### ISSUE THREAD

**Issue by tom-montgomery** [tom-montgomery/Replica2MXD#1]
this module is very limited in my opinion because it does not automatically create the replica mxd. Seems to require arc objects. Would love to update this.

**Comment by AlexArcPy** [comment]
@tom-montgomery , you are right that arcpy won't let you create a new empty .mxd file. However, there are some options. 

1. Use existing map templates which you can found in the ArcGIS installation folder, e.g. `C:\Program Files (x86)\ArcGIS\Desktop10.5\MapTemplates\Standard Page Sizes\ISO (A) Page Sizes`. They are empty with no layers added. Feel free to grab and use. You can get the installation directory using `arcpy.GetInstallInfo()`.

2. Use `comtypes` to create a new map document with the help of ArcObjects. I've created a gist for you [here](https://gist.github.com/AlexArcPy/bbba9a77866e34b9e3d55de39812b43c).

**Comment by tom-montgomery** [comment]
@AlexArcPy  Man thank you so much! I will keep you updated.

**Comment by tom-montgomery** [comment]
@AlexArcPy Updated the code to use the template MXD files in ArcGIS install directory, as I could only find snippets102 and it would not work with my 10.3.1 install. Thanks again man.

**Comment by AlexArcPy** [comment]
@tom-montgomery , glad you got it working. It's arguably the easiest way to get an empty map document and you don't have to rely on having `comtypes` installed. However, if you would like to experiment a bit, just replace the string `10.2` to `10.3.1` in the snippets module (2 places only), this is very easy.

More guidance at https://tereshenkov.wordpress.com/2016/01/16/accessing-arcobjects-in-python/
